Started at:
Friday February 27 at 02:05PM
Starting flashcard
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Started at:
Friday February 27 at 02:06PM
Starting flashcard
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Started at:
Friday February 27 at 02:07PM
Starting flashcard
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Started at:
Friday February 27 at 02:10PM
Starting flashcard
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Python error:

Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Python error:

Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Started at:
Friday February 27 at 02:12PM
Starting flashcard

Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/en-US_None_Salli_Here is some text spoken by a voice.ogg'

Message:
Exception error from the inner try in voice.py:
Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Python error:
Traceback (most recent call last):
  File "C:\Users\brandon\programming\PythonFiles\applications\flashcard\voice.py", line 150, in speak
    music.load(path)
error: Couldn't read from 'voice_files/My scripted deck 1-It is cool/None_None_Emma_That was good wasn't it.ogg'
Started at:
Wednesday March 04 at 02:24PM
Starting flashcard
